'''
Created on May 16, 2021

@author: Brett
'''
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestToPlayerList():
    def setup_method(self, method):
        self.driver = webdriver.Chrome(executable_path='/Users/Brett/Developer/chromedriver')
        self.vars = {}
  
    def teardown_method(self, method):
        self.driver.quit()
  
    def test_toPlayerList(self):
        self.driver.get("https://www.sangabrielcc.com/default.aspx?p=home&E=6")
        self.driver.set_window_size(1440, 878)
        self.driver.find_element(By.ID, "masterPageUC_MPCA166_ctl00_ctl01_txtUsername").click()
        self.driver.find_element(By.ID, "masterPageUC_MPCA166_ctl00_ctl01_txtUsername").send_keys("admin")
        self.driver.find_element(By.ID, "masterPageUC_MPCA166_ctl00_ctl01_txtPassword").send_keys("password")
        self.driver.find_element(By.ID, "masterPageUC_MPCA166_ctl00_ctl01_txtPassword").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(1) > .topnav_item:nth-child(1) li:nth-child(1) span").click()
        self.driver.find_element(By.LINK_TEXT, "18").click()
        self.driver.execute_script("window.scrollTo(0,400)")
        self.driver.find_element(By.LINK_TEXT, "3:40 PM").click()
        element = self.driver.find_element(By.LINK_TEXT, "3:40 PM")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()